# Generated by Django 6.0 on 2026-01-04 21:35

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='activation_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
